In [1]:
import pandas as pd

# Wczytanie danych z pliku CSV do obiektu DataFrame za pomocą biblioteki pandas
data = pd.read_csv("mushrooms.csv")

In [2]:
from numpy import ndarray

def prepare_data_sets(number_of_used_attributes: int) -> list[ndarray, ndarray]:
    """Prepares data sets (columns/attributes) and labels for testing..

    Args:
        number_of_used_attributes (int): number of attributes from we'll create datasets.

    Returns:
        list[ndarray, ndarray]: dataset and target ndarray.
    """
    try:
        dataset = data.values[:, 1:number_of_used_attributes]
        target = data.values[:, 0]
        return dataset, target
    except Exception as error:
        print(f"An unexpected error: {error} while preparing data sets.")

In [3]:
attributes: int = 22  # maximum value that we can test.
dataset, target = prepare_data_sets(attributes)

In [4]:
from sklearn import preprocessing

def convert_labels_and_attributes_to_numeric_values(number_of_used_attributes: int, dataset: ndarray, target: ndarray) -> None:
    """Convert labels (edible/non-edible) and attributes to numeric values using LabelEncoder
    
    Args:
        number_of_used_attributes (int): number of attributes from we'll create datasets.
        dataset (ndarray): dataset array.
        target (ndarray): target array.
    """
    try:
        label_encoder = preprocessing.LabelEncoder()
        target = label_encoder.fit_transform(target)
        for x in range(0, number_of_used_attributes - 1):
            dataset[:, x] = label_encoder.fit_transform(dataset[:, x])
    except Exception as error:
        print(f"An unexpected error: {error} while converting labels to numeric values.")

In [5]:
convert_labels_and_attributes_to_numeric_values(attributes, dataset, target)

In [6]:
from sklearn.model_selection import train_test_split

def splits_data_for_testing(_test_size: float) -> list:
    """Splits the data into a training set and a test set.

    Args:
        _test_size (float): proportion of the dataset to include in the train split.

    Returns:
        list: list of training and testing data and target.
    """
    try:
        training_data, testing_data, training_target, testing_target = \
            train_test_split(dataset, target.reshape(-1, 1), test_size=_test_size)
        return training_data, testing_data, training_target, testing_target
    except Exception as error:
        print(f"An unexpected error: {error} while splitting data for testing.")

In [7]:
training_data, testing_data, training_target, testing_target = \
    splits_data_for_testing(0.1)

In [8]:
from sklearn.tree import DecisionTreeClassifier

def train_decision_tree_model(_max_depth: int) -> ndarray:
    """Initializes and trains of the decision tree model.

    Args:
        _max_depth (int): max depth of the decision tree.

    Returns:
        ndarray: the predicted class for each sample in X is returned.
    """
    global training_data, training_target, testing_data
    try:
        decision_tree = DecisionTreeClassifier(criterion='entropy', max_depth=_max_depth)
        decision_tree.fit(training_data, training_target)
        return decision_tree.predict(testing_data)
    except Exception as error:
        print(f"An unexpected error: {error} while training decision tree model.")

In [9]:
decision_predict_tree_array = train_decision_tree_model(8)

In [10]:
from sklearn.metrics import confusion_matrix

def print_confusion_matrix(decision_predict_tree_array: ndarray) -> None:
    """Prints confusion matrix.

    Args:
        decision_predict_tree_array (ndarray): the predicted class for each sample in X is returned.
    """
    try:
        print("Confusion Matrix:")
        print(f"{confusion_matrix(testing_target, decision_predict_tree_array)}\n")
    except Exception as error:
        print(f"An unexpected error: {error} while printing confusion matrix.")

In [11]:
from sklearn.metrics import accuracy_score

def print_accuracy_score(decision_predict_tree_array: ndarray) -> None:
    """Prints accuracy score.

    Args:
        decision_predict_tree_array (ndarray): the predicted class for each sample in X is returned.
    """
    try:
        print("Accuracy score:")
        print(accuracy_score(testing_target, decision_predict_tree_array))
    except Exception as error:
        print(f"An unexpected error: {error} while printing accuracy score.")

In [12]:
def test_data_accuracy(number_of_used_attributes: int, _test_size: float, _max_depth: int) -> None:
    """Test data accuracy in case of some variables.

    Args:
        number_of_used_attributes (int): number of attributes from we'll create datasets.
        _test_size (float): proportion of the dataset to include in the train split.
        _max_depth (int): max depth of the decision tree.
    """
    try:
        dataset, target = prepare_data_sets(number_of_used_attributes)
        convert_labels_and_attributes_to_numeric_values(number_of_used_attributes, dataset, target)
        training_data, testing_data, training_target, testing_target = \
            splits_data_for_testing(_test_size)
        
        for _ in range(_max_depth):
            print(f"\nActual tree max depth: {_max_depth - _}: \n")
            decision_predict_tree_array = train_decision_tree_model(_max_depth - _)
            print_confusion_matrix(decision_predict_tree_array)
            print_accuracy_score(decision_predict_tree_array)
    except IndexError as index_error:
        print(f"IndexError: {index_error} while testing data.")
    except Exception as error:
        print(f"An unexpected error: {error} while testing data.")

In [13]:
test_data_accuracy(22, 0.1, 8)
        



Actual tree max depth: 8: 

Confusion Matrix:
[[446   0]
 [  0 367]]

Accuracy score:
1.0

Actual tree max depth: 7: 

Confusion Matrix:
[[445   1]
 [  0 367]]

Accuracy score:
0.998769987699877

Actual tree max depth: 6: 

Confusion Matrix:
[[441   5]
 [  1 366]]

Accuracy score:
0.992619926199262

Actual tree max depth: 5: 

Confusion Matrix:
[[439   7]
 [  7 360]]

Accuracy score:
0.982779827798278

Actual tree max depth: 4: 

Confusion Matrix:
[[421  25]
 [ 12 355]]

Accuracy score:
0.9544895448954489

Actual tree max depth: 3: 

Confusion Matrix:
[[421  25]
 [ 12 355]]

Accuracy score:
0.9544895448954489

Actual tree max depth: 2: 

Confusion Matrix:
[[439   7]
 [ 49 318]]

Accuracy score:
0.931119311193112

Actual tree max depth: 1: 

Confusion Matrix:
[[446   0]
 [208 159]]

Accuracy score:
0.7441574415744158
